const PROCESS_OPERATIONS = {
  READIMAGE: "basic_readimage",
  WRITEIMAGE: "basic_writeimage",
  REFLECTIMAGE: "geometric_reflectimage",
  ROTATEIMAGE: "geometric_rotateimage",
  AFFINEIMAGE: "geometric_affineimage",
  SCALEIMAGE: "geometric_scaleimage",
  GRAYIMAGE:"imageconvertions_grayimage",
  GRAYTOBINARY:"imageconvertions_graytobinary",
  DRAWLINE: "drawingoperations_drawline",
  DRAWELLIPSE: "drawingoperations_drawellipse",
  DRAWARROWLINE: "drawingoperations_drawarrowline",
  DRAWTEXT: "drawingoperations_drawtext",
  DRAWCIRCLE: "drawingoperations_drawcircle",
  DRAWRECTANGLE: "drawingoperations_drawrectangle",
  BLURIMAGE: "blurring_applyblur",
  GAUSSIANBLUR: "blurring_applygaussianblur",
  MEDIANBLUR: "blurring_applymedianblur",
  BILATERALFILTER: "filtering_bilateral",
  BOXFILTER: "filtering_boxfilter",
  PYRAMIDUP: "filtering_pyramidup",
  PYRAMIDDOWN: "filtering_pyramiddown",
  EROSION: "filtering_erosion",
  DILATION: "filtering_dilation",
  SOBLEDERIVATE: "edgedetection_soblederivate",
  SCHARRDERIVATE: "edgedetection_scharrderivate",
  LAPLACIAN: "edgedetection_laplacian",
  CANNYEDGE: "edgedetection_cannyedge",
  MORPHOLOGICAL: "filtering_morphological",
  SIMPLETHRESHOLDING: "thresholding_applythreshold",
};

module.exports = PROCESS_OPERATIONS;
